#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_inform
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom ggplot2 %+replace%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 autoplot
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 position_dodge2
#' @importFrom ggplot2 position_fill
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 sec_axis
#' @importFrom ggplot2 vars
#' @importFrom glue glue
#' @importFrom patchwork wrap_plots
#' @importFrom pillar type_sum
#' @importFrom purrr map
#' @importFrom purrr map_lgl
#' @importFrom purrr pluck
#' @importFrom purrr pmap
#' @importFrom rlang .data
#' @importFrom rlang abort
#' @importFrom rlang as_quosures
#' @importFrom rlang current_env
#' @importFrom rlang enquo
#' @importFrom rlang names2
#' @importFrom rlang quo_name
#' @importFrom rlang syms
#' @importFrom rlang warn
#' @importFrom scales label_percent
#' @importFrom stats IQR
#' @importFrom stats median
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats t.test
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr unnest
## usethis namespace: end
NULL
